language: php
os:
  - linux
php:
  - 7.2
services:
  - mysql
install:
  - composer self-update
  - travis_retry composer install --no-interaction --no-scripts --prefer-source --dev
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
  - mysql -e 'use myapp_test;CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(255) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL);'
  - mysql -e 'use myapp_test;CREATE TABLE posts (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id));'
script:
 - composer test
 - composer lint
 - npm run lint
