language: php
os:
  - linux
php:
  - 7.2
services:
  - mysql
install:
  - composer self-update
  - travis_retry composer install --no-interaction --no-scripts --prefer-source --dev
before_script:
  - mysql -e 'CREATE DATABASE myapp_test;'
script: phpunit --strict-coverage
